
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7003048,'reActivateCustomer failed: No Record found for Activation After Stored Proc Called.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7003043,'reActivateCustomer failed: NO Contract Found for reActivate Customer');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7003047,'reActivateCustomer failed: JDBC (OCON) Connection Failed for Stored Proc Call.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7003045,'reActivateCustomer failed: Failed to process ReActivation');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7003042,'deleteCustomer failed: NO Contract Found for Soft Delete.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7003044,'deleteCustomer failed: Failed to process Soft Delete.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (100104,'XCreateDt cannot be updated.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (9000022,'XBUID is requied at XAdminNativeKey Object');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (9000055,'Update on Full Company Name is not allowed');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1000475,'Update of the following failed: XPerson.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1003723,'Update of the following failed: XPartyIdentification.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1000923,'Update of the following failed: XPartyContactMethod.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1000834,'Update of the following failed: XPartyAddress.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1000414,'Update of the following failed: XParty.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1002600,'Update of the following failed: XOrganization.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004511,'Update of the following failed: XContractRoleLocationPurpose.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1001183,'Update of the following failed: XContractRoleLocation.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1003043,'Update of the following failed: XContractRole.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1002484,'Update of the following failed: XContractRelationship.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1003556,'Update of the following failed: XContractPartyRoleRelationship.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1001106,'Update of the following failed: XContractComponent.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1000980,'Update of the following failed: XContract.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004916,'Update of the following failed: XContactMethod.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1000540,'Update of the following failed: XContEquiv.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004867,'Update of the following failed: XAddress.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1002898,'Update of the following failed: CAMSrcUpdRule.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1000278,'Update of the following failed: CAMSalesRep.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004249,'Update of the following failed: CAMRoleResponsibility.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (2004734,'Update of the following failed: CAMEndUserAuthXRef.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1006006,'Update of the following failed: CAMDNRoleAddrGroup.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1006101,'Update of the following failed: CAMDNContMethGroup.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004397,'Update of the following failed: CAMBUIdXref.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004608,'The format of the following is not correct: inquireAsOfDate.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1006069,'The format of the following is not correct: inquireAsOfDate.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004217,'The format of the following is not correct: inquireAsOfDate.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004365,'The format of the following is not correct: inquireAsOfDate.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004552,'The format of the following is not correct: inquireAsOfDate.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004579,'The format of the following is not correct: inquireAsOfDate.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1005974,'The format of the following is not correct: inquireAsOfDate.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (2004702,'The format of the following is not correct: inquireAsOfDate.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1002866,'The format of the following is not correct: inquireAsOfDate.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1000246,'The format of the following is not correct: inquireAsOfDate.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1002527,'The format of the following is not correct: inquireAsOfDate.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004637,'The format of the following is not correct: inquireAsOfDate.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1002429,'The format of the following is not correct: inquireAsOfDate.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1003934,'The following transaction failed: searchCustomer.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1002404,'The following transaction failed: searchCAMContract.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004806,'The following transaction failed: retrofitServiceHelper.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1003990,'The following transaction failed: reActivateCustomer.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1001954,'The following transaction failed: maintainCAMParty.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1001968,'The following transaction failed: maintainCAMContract.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1002555,'The following transaction failed: getTopNContractAlerts.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1003948,'The following transaction failed: getRelatedCustomerNumbers.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1003939,'The following transaction failed: getCamLocationIds.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1001982,'The following transaction failed: getCAMHashkey.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1003976,'The following transaction failed: deleteCustomer.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (3000119,'The following transaction failed: RetrofitUSCAMContract.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (4011085,'The following transaction failed: RefreshCAMXREFTable.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1005850,'The following is required: stn_info_tp_cd');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1005911,'The following is required: stn_info_tp_cd');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1003904,'The following is required: state_country_tp_cd');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1002795,'The following is required: role_loc_st_tp_cd');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1000785,'The following is required: rm_num_tp_cd');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1003912,'The following is required: name');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1000151,'The following is required: name');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1006550,'The following is required: name');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1002803,'The following is required: name');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1002750,'The following is required: name');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1005858,'The following is required: name');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1005919,'The following is required: name');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1006561,'The following is required: contract_st_tp_cd');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1006542,'The following is required: contract_st_reason_tp_cd');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1002742,'The following is required: contr_role_st_tp_cd');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004133,'The following is required: buid_tp_cd');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1001831,'The following is required: XStartDate');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1003246,'The following is required: XSalesChannel');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1003833,'The following is required: XPaymentTermCode');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1003825,'The following is required: XEndUserAuthCode');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1002496,'The following is required: XCAMLocationId');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (4011029,'The following is required: TableName');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1001847,'The following is required: StartDate');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1002932,'The following is required: StartDate');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (2004756,'The following is required: SalesChannelId');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (4011035,'The following is required: PreviousMapSize');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1006195,'The following is required: PartyType');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1006155,'The following is required: PartyId');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1006383,'The following is required: PartyId');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004141,'The following is required: Name');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (4011065,'The following is required: MapValue');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (4011059,'The following is required: MapKey');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1006487,'The following is required: LocationGroupId');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1006447,'The following is required: LocationGroupId');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (2004764,'The following is required: LinkedCurrencyCode');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004440,'The following is required: LinkedBuidStr');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004408,'The following is required: LangTpCd');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (2004740,'The following is required: LangTpCd');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1002926,'The following is required: EntityName');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (2004748,'The following is required: EndUserAuthCode');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (4011041,'The following is required: CurrentMapSize');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1002912,'The following is required: CreatedSource');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1006391,'The following is required: ContractRoleType');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1006481,'The following is required: ContractRoleType');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1006301,'The following is required: ContractRoleId');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1006407,'The following is required: ContractRoleId');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1006275,'The following is required: ContractId');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1000290,'The following is required: ContractId');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1006283,'The following is required: ContractComponentId');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1006399,'The following is required: ContractComponentId');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1006439,'The following is required: ContactMethodType');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1006459,'The following is required: ContactMethodId');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1006343,'The following is required: ConatrctId');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1002837,'The following is required: CAMSrcUpdRuleIdPk');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1000217,'The following is required: CAMSalesRepIdPk');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004188,'The following is required: CAMRoleResponsibilityIdPk');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (2004673,'The following is required: CAMEndUserAuthXRefIdPk');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1005945,'The following is required: CAMDNRoleAddrGrouppkId');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1006040,'The following is required: CAMDNContMethGrouppkId');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004336,'The following is required: CAMBUIdXrefIdPk');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004424,'The following is required: BuidReferenceValue');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004416,'The following is required: BuidReferenceType');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004432,'The following is required: BuidReferenceDataCategory');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1006367,'The following is required: Buid');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1006123,'The following is required: Buid');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1006359,'The following is required: AdminContractId');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1006115,'The following is required: AdminContractId');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1006335,'The following is required: AddressId');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004148,'The following is not correct: country_tp_cd');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1006557,'The following is not correct: contract_st_tp_cd');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1000552,'The following is not correct: XStartDate');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1003624,'The following is not correct: XSplitToPurpose');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1003587,'The following is not correct: XSplitFromPurpose');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1002983,'The following is not correct: XRoleLocSt');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1003063,'The following is not correct: XInactReason');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1002996,'The following is not correct: XInactReason');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1002970,'The following is not correct: XInactReason');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1000564,'The following is not correct: XEndDate');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1001909,'The following is not correct: XCreateDt');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1001843,'The following is not correct: XCreateDt');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1001897,'The following is not correct: XCreateDt');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1001118,'The following is not correct: XContractStDate');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1003050,'The following is not correct: XContrRoleSt');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004290,'The following is not correct: StartDate');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1003315,'The following is not correct: StartDate');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1000348,'The following is not correct: StartDate');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004272,'The following is not correct: RolePurpose');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1006453,'The following is not correct: RoleLocationEndDate');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1006313,'The following is not correct: RoleLocationEndDate');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1001669,'The following is not correct: RepAssignedDate');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1000355,'The following is not correct: RMNUM');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1006329,'The following is not correct: PartyInactivatedDate');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004404,'The following is not correct: LangTpCd');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004454,'The following is not correct: ExpiryDate');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (2004778,'The following is not correct: ExpiryDate');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (9000027,'The following is not correct: EndUserAuthCode <EndUserAuthCode> and SalesChannelId <SalesChannelId> for given Currency Code <Currency_Val>');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004302,'The following is not correct: EndDate');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1003282,'The following is not correct: EndDate');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1001673,'The following is not correct: EndDate');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1006325,'The following is not correct: ContractRoleEndDate');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1006289,'The following is not correct: ContractEndDate');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (9000021,'The following is not correct: <ATTRIBUTE_TYPE> or <ATTRIBUTE_VALUE>');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (9000020,'The following is not correct: <ATTRIBUTE_TYPE> and <ATTRIBUTE_VALUE> for BUID <BUID>');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (70000153,'The following is not correct : XInactivatedReasonType and ContractStatusType');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (2004698,'The following is incorrect: id is null.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1005970,'The following is incorrect: id is null.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004604,'The following is incorrect: id is null.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1000242,'The following is incorrect: id is null.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004213,'The following is incorrect: id is null.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004361,'The following is incorrect: id is null.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004548,'The following is incorrect: id is null.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004575,'The following is incorrect: id is null.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004633,'The following is incorrect: id is null.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1002425,'The following is incorrect: id is null.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1002523,'The following is incorrect: id is null.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1002862,'The following is incorrect: id is null.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1006065,'The following is incorrect: id is null.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004088,'The following is incorrect: SearchCAMCustomer has a child CAMCustomerSearch but the reference in CAMCustomerSearch is present and does not match the id from SearchCAMCustomer');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004070,'The following is incorrect: CAMCustomerSearch has a child PartialContractAdminSysKey but the reference in PartialContractAdminSysKey is present and does not match the id from CAMCustomerSearch');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004008,'The following is incorrect: CAMContractSearch has a child ContractSearch but the reference in ContractSearch is present and does not match the id from CAMContractSearch');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1002841,'The before image for the following is empty: CAMSrcUpdRule.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1000221,'The before image for the following is empty: CAMSalesRep.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004192,'The before image for the following is empty: CAMRoleResponsibility.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (2004677,'The before image for the following is empty: CAMEndUserAuthXRef.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1005949,'The before image for the following is empty: CAMDNRoleAddrGroup.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1006044,'The before image for the following is empty: CAMDNContMethGroup.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004340,'The before image for the following is empty: CAMBUIdXref.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (9000026,'The Given Party Address / Party Contact Method ID PK is not valid');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7003037,'The Funder relationship has been inactivated. Please submit a 3rd Party Financing Credit Request in DSA or contact the US_Flooring_Orders_Expedite@Dell.com for assistance.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (9000059,'ServiceOrgName is required for AgreementFullName');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (100100,'SearchCAMContract failed: Wrong inquiry level for either contract or party level.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (100102,'SearchCAMContract failed: No contracts found for given search.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (100107,'SearchCAMContract failed: No contacts found for given customer.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (100101,'SearchCAMContract failed: Insufficient input data to search.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (100103,'SearchCAMContract failed: Incorrect party pagination parameters.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7003036,'Sales channel cannot be updated on a funder account');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1002858,'Read of the following record failed: CAMSrcUpdRule.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1000238,'Read of the following record failed: CAMSalesRep.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1002421,'Read of the following record failed: CAMSalesRep.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1002519,'Read of the following record failed: CAMSalesRep.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004209,'Read of the following record failed: CAMRoleResponsibility.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (2004694,'Read of the following record failed: CAMEndUserAuthXRef.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1005966,'Read of the following record failed: CAMDNRoleAddrGroup.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1006061,'Read of the following record failed: CAMDNContMethGroup.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004629,'Read of the following record failed: CAMBUIdXref.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004357,'Read of the following record failed: CAMBUIdXref.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004544,'Read of the following record failed: CAMBUIdXref.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004571,'Read of the following record failed: CAMBUIdXref.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004600,'Read of the following record failed: CAMBUIdXref.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1000471,'Read of the following failed: XPerson.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1003719,'Read of the following failed: XPartyIdentification.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1000919,'Read of the following failed: XPartyContactMethod.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1000830,'Read of the following failed: XPartyAddress.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1000410,'Read of the following failed: XParty.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1002596,'Read of the following failed: XOrganization.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004507,'Read of the following failed: XContractRoleLocationPurpose.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1001179,'Read of the following failed: XContractRoleLocation.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1003039,'Read of the following failed: XContractRole.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1002480,'Read of the following failed: XContractRelationship.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1003552,'Read of the following failed: XContractPartyRoleRelationship.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1001102,'Read of the following failed: XContractComponent.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1000976,'Read of the following failed: XContract.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004912,'Read of the following failed: XContactMethod.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1000536,'Read of the following failed: XContEquiv.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004863,'Read of the following failed: XAddress.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (9000054,'PurposeType mismatch identified in CONTACT address role location and role responsibility');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (9000028,'Phone Country Code length should be 3');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (6000005,'Party Created by <parm> cannot be updated by <parm>');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (9000024,'Owner Role is mandatory for customer creation');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (9000109,'Not able to retrieve DB address role location as either one or both of XOwnerSiteLocationId and XOwnerSiteRoleLocationId is null');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (6000006,'No matching parties found for the combination XCAMLocationId and purpose type.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7003002,'Invalid link number for Relationship.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7000011,'Invalid PurposeType for Phone RoleLocation.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7000010,'Invalid PurposeType for PartyAddress RoleLocation.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7000012,'Invalid PurposeType for Email RoleLocation.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (9000058,'Invalid Provider Reason for Full Company Name.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7003001,'Invalid Invoice Delivery Method Indicator for Primary Billing/Billing Address.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1000463,'Insert of the following failed: XPerson.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1003711,'Insert of the following failed: XPartyIdentification.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1000911,'Insert of the following failed: XPartyContactMethod.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1000822,'Insert of the following failed: XPartyAddress.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1000402,'Insert of the following failed: XParty.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1002588,'Insert of the following failed: XOrganization.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004499,'Insert of the following failed: XContractRoleLocationPurpose.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1001171,'Insert of the following failed: XContractRoleLocation.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1003031,'Insert of the following failed: XContractRole.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1002472,'Insert of the following failed: XContractRelationship.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1003544,'Insert of the following failed: XContractPartyRoleRelationship.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1001094,'Insert of the following failed: XContractComponent.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1000968,'Insert of the following failed: XContract.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004904,'Insert of the following failed: XContactMethod.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1000528,'Insert of the following failed: XContEquiv.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004855,'Insert of the following failed: XAddress.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1002881,'Insert of the following failed: CAMSrcUpdRule.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1000261,'Insert of the following failed: CAMSalesRep.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004232,'Insert of the following failed: CAMRoleResponsibility.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (2004717,'Insert of the following failed: CAMEndUserAuthXRef.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1005989,'Insert of the following failed: CAMDNRoleAddrGroup.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1006084,'Insert of the following failed: CAMDNContMethGroup.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004380,'Insert of the following failed: CAMBUIdXref.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (8000002,'Incomplete Customer Information (Missing either PrimaryBilling/PrimaryShipping/Owner contacts), please try again after some time..');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (9000023,'Given BUID is not valid');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (9000009,'GetRelatedCustomerNumbers failed: Top Level Object is invalid');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (9000012,'GetRelatedCustomerNumbers failed: No Data found for Given Search.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (9000011,'GetRelatedCustomerNumbers failed: Incorrect pagination parameters');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (9000010,'GetRelatedCustomerNumbers failed: AdminContractId or BusOrgunitId or XContractRelType is not present');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (9000005,'GetCamLocationIds failed: Top Level Object is invalid');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (9000008,'GetCamLocationIds failed: No Data found for Given Search.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (9000007,'GetCamLocationIds failed: Incorrect pagination parameters.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (9000006,'GetCamLocationIds failed : Either AdminContractId or BusOrgunitId is not present');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (800101,'Exception in invoking Event Manager to check for Value Package integrity');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7003032,'ErrorMessage: Updating the UndelReasonTp for Shipping role is not allowed');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7003021,'ErrorMessage: Invalid Address');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7003022,'ErrorMessage: Invalid Address');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (9000101,'Error:: Invalid XREF Table Provided');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (9000102,'Error:: Failed to process XREF table.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7000031,'Error: XModifyBy is mandatory during Create and Update Customer At Contract level.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7000018,'Error: Unable To Establish JDBC Connection');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7000009,'Error: The Following is Required Contract Currency Type.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7000017,'Error: The Following Is Required : XCreateBy during create customer at Contract level.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7000024,'Error: The Following Is Required : TCRMContractRoleLocationBObj.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7000023,'Error: The Following Is Required : TCRMContractPartyRoleBObj.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7000022,'Error: The Following Is Required : TCRMContractComponentBObj.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7000015,'Error: The Following Is Required : CAMSalesRepBObj.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7000021,'Error: The Following Is Required : AgreementName');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7000016,'Error: The Following Is Not Active : CAMSalesRepBObj.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7000027,'Error: TCRMContractRoleLocationPurposeBObj Is Mandatory At TCRMContractRoleLocationBObj.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7000019,'Error: SQL Execution Error');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (8000001,'Error: Povided Link Customer does not match to any active contract');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7000035,'Error: PartyAddress is mandatory for new party');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7000028,'Error: Oracle Sequence Does not exits');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (100106,'Error: No Record Found For Search Party.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7000020,'Error: No Record Found For Search Contract.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7000025,'Error: ContractRoleType cannot be updated.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7000029,'Error: Atleast one active primary CAMSalesRepBObj is required.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7000026,'Error: At Least One TCRMPartyAddressBObj Is Mandatory At TCRMContractRoleLocationBObj.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (8003052,'Error :: No Duns Number found for given Request.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (8003054,'Error :: More Than One Party Found for given Duns Number.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (8003053,'Error :: CAM CreditPartySync Failed to process PreExecute.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7000211,'ERROR:Account <ADMIN_CONTRACT_ID> does not have a Business Contact Address. Contact CMDM for assistance');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7000013,'ERROR: “Provided ReplaceContract does not match to any active Contract');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7000104,'ERROR: XSplitToPurposeType is Mandatory');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7000101,'ERROR: XSplitToCustomerNumber is Mandatory');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7000103,'ERROR: XSplitToCAMLocationId is Mandatory');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7000102,'ERROR: XSplitToAddrSeqNum is Mandatory');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7000108,'ERROR: XSplitFromPurposeType is Mandatory');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7000105,'ERROR: XSplitFromCustomerNumber is Mandatory');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7000107,'ERROR: XSplitFromCAMLocationId is Mandatory');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7000106,'ERROR: XSplitFromAddrSeqNum is Mandatory');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7000045,'ERROR: XPaymentTermType cannot be a Legacyvalue for NON DOMS RequesterName.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7000044,'ERROR: XPaymentTermType Cannot be blank when AgreementType {1000001} for NON-DOMS Source');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7000048,'ERROR: XLegacyContractId is Mandatory For Doms Source.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7000100,'ERROR: XLegacyCompanyName is Mandatory');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7003018,'ERROR: Validation for Partner / Vendor / End User / Retailer relationships');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7000001,'ERROR: The Following is Required : TCRMContractBObj.getBusOrgunitId');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7003016,'ERROR: RoleLocation status type cannot be updated to null.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7003012,'ERROR: RoleLocation status type cannot be inactive for Primary Billing or Primary Shipping or Primary Mailing Address.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7003013,'ERROR: RoleLocation cannot be end dated for Primary Billing or Primary Shipping or Primary Mailing Address.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7003007,'ERROR: Role type can not be end dated for Primary RoleType.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7003017,'ERROR: Role status type cannot be updated to null.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7003009,'ERROR: Role Type cannot be updated from Primay Shipping to Shipping : Atleast one Primary Shipping RoleType is required');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7003010,'ERROR: Role Type cannot be updated from Primay Mailing to Mailing : Atleast one Primary Mailing RoleType is required');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7003008,'ERROR: Role Type cannot be updated from Primay Billing to Billing : Atleast one Primary Billing RoleType is required');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7003023,'ERROR: Retailer, Partner, Vendor and End User relationship are only between two customer accounts/Link accounts');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7000046,'ERROR: RepNum is Mandatory For Non-Doms Source');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7000047,'ERROR: RMNUMType is Mandatory For Non-Doms Source');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7003005,'ERROR: Primary Billing/Primary Shipping/Primary Mailing role type can not be end dated.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7000041,'ERROR: Phone Number is Mandatory for Person for NON-DOMS Source.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7000043,'ERROR: Phone Number is Mandatory for Org for NON-DOMS Source.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (8000050,'ERROR: Occured while Converting Legacy state model to feature state model');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7003024,'ERROR: Link relationship type is only between customer account and link account');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7003015,'ERROR: Invalid State and Country Code combination.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7000049,'ERROR: Input Request is having Only One ContractPartyRole of Role Type Owner{1000005}');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7000032,'ERROR: Input Request having more than one primary billing contact. {Role Type 1000001}');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7000033,'ERROR: Input Request having more than one primary Shipping contact. {Role Type 1000003}');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7000034,'ERROR: Input Request having more than one Primary Mailing Contact. {Role Type 1000007}');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7003025,'ERROR: Funder/Floorer relationship type is only between  customer account/Link account and  funder account');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7003027,'ERROR: For a Split Customer, PrimaryBilling and Billing Contact is not applicable.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7003028,'ERROR: For a Shipping Only Customer,adding a Billing or Primary Billing address is not Possible');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7000039,'ERROR: For Shipping RoleType{1000003,1000004} purposeType must be of Shipping {1000031,1000002} only For Address.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7000007,'ERROR: For NON DOMS request PrimaryBilling/Billing Contact is mandatory for Add Contract');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7000038,'ERROR: For Mailing RoleType{1000007,1000008} purposeType must be of Mailing {1000029,1000003} only For Address.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7000008,'ERROR: For DOMS request PrimaryBilling/Billing Contact is mandatory for NON Split Customers during Add Contract.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7000040,'ERROR: For Billing RoleType{1000001,1000002} purposeType must be of Billing {1000030,1000001} only For Address.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (8003055,'ERROR: Failed to process maintainCAMParty for CreditPartySync.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7000042,'ERROR: Email is Mandatory for Person for NON_DOMS Source.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7003011,'ERROR: Cross Role Type cannot be updated.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7003004,'ERROR: Contract status type cannot be inactive for Primary role type.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7003006,'ERROR: Contract status type cannot be inactive for Primary RoleType.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7003014,'ERROR: Contract status type cannot be inactive for Person Owner role type.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7000050,'ERROR: At least one RoleType of 1000001 or 1000002 is reuried for overall Contract');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7003026,'ERROR: 3rd Party Leasing relationship type is only between active customer account and active funder account');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7000014,'ERROR:  Person Party must be Required with Org Party');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7000051,'ERROR :CAM Account is already part of another CAM Credit Party <ADMINPARTYID>');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7003046,'ERROR : Stored Procedure failed to process Hard Delete Activation with ErrorCode <PROC_ERROR_CODE>');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7000030,'ERROR : Pending DNBMatchValidation for this Contract, cannot add New Billing Site until DNBMatch Validation is completed.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7000037,'ERROR : HQ DUNS number is mandatory for Credit Org Party');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7003034,'ERROR : Funder relationship not created because customer / funder sales channels do not match');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7003029,'ERROR : For Batch Flow, A contract can be updated only if it is in Active state');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7000036,'ERROR : Contract Does not exist, cannot create a Credit Pary without an existing Contract');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7003030,'ERROR : (<Sales_Channel> : Previous Sales Channel is not in the DellPrint Path)');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7003033,'ERROR :  Site Duns does not belong to Hqduns of existing Credit party');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7003038,'ERROR :  Only DSA can set the Contract Status Status to SH');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7003039,'ERROR :  Contract Status can be set to SH by DSA only if the Contract Status/RoleLocation Status is A');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7003041,'ERROR :  Contract Status can be set to A, H, D or S  from SH by OMEGA');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7003040,'ERROR :  Contract Status can be set to A  from SH only by DSA or OMEGA');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7003031,'ERROR :  (<Sales_Channel> : Current Sales Channel is not in the DellPrint Path)');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1000265,'Duplicate primary key already exists.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004384,'Duplicate primary key already exists.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004236,'Duplicate primary key already exists.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1006088,'Duplicate primary key already exists.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1002885,'Duplicate primary key already exists.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1005993,'Duplicate primary key already exists.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (2004721,'Duplicate primary key already exists.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (9000053,'Duplicate Purpose Type in RoleLocationPurpose');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (9000052,'Duplicate Purpose Type in CAMRoleResponsibility');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1000467,'Delete of the following failed: XPerson.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1003715,'Delete of the following failed: XPartyIdentification.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1000915,'Delete of the following failed: XPartyContactMethod.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1000826,'Delete of the following failed: XPartyAddress.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1000406,'Delete of the following failed: XParty.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1002592,'Delete of the following failed: XOrganization.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004503,'Delete of the following failed: XContractRoleLocationPurpose.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1001175,'Delete of the following failed: XContractRoleLocation.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1003035,'Delete of the following failed: XContractRole.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1002476,'Delete of the following failed: XContractRelationship.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1003548,'Delete of the following failed: XContractPartyRoleRelationship.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1001098,'Delete of the following failed: XContractComponent.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1000972,'Delete of the following failed: XContract.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004908,'Delete of the following failed: XContactMethod.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1000532,'Delete of the following failed: XContEquiv.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004859,'Delete of the following failed: XAddress.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (2008000,'DWLControl Event Ids are null ');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7003019,'Customer is not of link type to establish a link relationship');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (9000051,'Currency value is invalid');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (9000025,'Currency is not updatable');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (2008003,'Creditor Party doesn''t exist in CA DB for retrofit update case');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (100105,'Contracts in Deactive Status are not updatable.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (2008001,'Contract not found in Legacy DB');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (2008002,'Contract not found in CA DB for retrofit update case');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (6000004,'Contract Created by <parm> cannot be updated by <parm>');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (9000057,'AgreementFullName cannot be null for given ServiceOrgName.');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7003003,'A new Billing site cannot be added until a Credit party is created for this Customer');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (6000003,'A contractrole once is in InActive status, cannot be updated');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (6000002,'A contract once is in DeActive status, cannot be updated');
Insert into CDERR (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (6000001,'A contract cannot have more than one active owner.');
