REM INSERTING into CDERRMESSAGETP
SET DEFINE OFF;
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008782,'reActivateCustomer failed: No Record found for Activation After Stored Proc Called.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008766,'reActivateCustomer failed: NO Contract Found for reActivate Customer.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008566,'reActivateCustomer failed: JDBC (OCON) Connection Failed for Stored Proc Call.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008762,'deleteCustomer failed: NO Contract Found for Soft Delete.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008770,'deleteCustomer failed: Failed to process Soft Delete.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008354,'XCreateDt cannot be updated.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008988,'Update on UndelReasonTp not allowed for Non-Billing address');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004903,'Update of the following failed: XPersonName.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1000475,'Update of the following failed: XPerson.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1003723,'Update of the following failed: XPartyIdentification.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1000923,'Update of the following failed: XPartyContactMethod.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1000834,'Update of the following failed: XPartyAddress.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1006828,'Update of the following failed: XParty.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1005097,'Update of the following failed: XOrganizationName.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1002600,'Update of the following failed: XOrganization.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004511,'Update of the following failed: XContractRoleLocationPurpose.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1001183,'Update of the following failed: XContractRoleLocation.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1003043,'Update of the following failed: XContractRole.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1002484,'Update of the following failed: XContractRelationship.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1003556,'Update of the following failed: XContractPartyRoleRelationship.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1001106,'Update of the following failed: XContractComponent.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1000980,'Update of the following failed: XContract.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1007997,'Update of the following failed: XContactMethod.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1000540,'Update of the following failed: XContEquiv.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1007109,'Update of the following failed: XAdminNativeKey.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004976,'Update of the following failed: XAddress.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1005515,'Update of the following failed: CAMTaxIdentifier.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1002898,'Update of the following failed: CAMSrcUpdRule.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1000278,'Update of the following failed: CAMSalesRep.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004249,'Update of the following failed: CAMRoleResponsibility.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004734,'Update of the following failed: CAMEndUserAuthXRef.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1007519,'Update of the following failed: CAMDNRoleAddrGroup.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1007614,'Update of the following failed: CAMDNContMethGroup.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004397,'Update of the following failed: CAMBUIdXref.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008989,'Two contacts cannot have same giicontactId within a BUID');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008726,'The source and target parties cannot be the same');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1007487,'The format of the following is not correct: inquireAsOfDate.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1002429,'The format of the following is not correct: inquireAsOfDate.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1002527,'The format of the following is not correct: inquireAsOfDate.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1006783,'The format of the following is not correct: inquireAsOfDate.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004217,'The format of the following is not correct: inquireAsOfDate.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1002866,'The format of the following is not correct: inquireAsOfDate.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004702,'The format of the following is not correct: inquireAsOfDate.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004637,'The format of the following is not correct: inquireAsOfDate.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004608,'The format of the following is not correct: inquireAsOfDate.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004579,'The format of the following is not correct: inquireAsOfDate.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004552,'The format of the following is not correct: inquireAsOfDate.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004365,'The format of the following is not correct: inquireAsOfDate.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1007582,'The format of the following is not correct: inquireAsOfDate.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1000246,'The format of the following is not correct: inquireAsOfDate.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1005483,'The format of the following is not correct: inquireAsOfDate.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1006316,'The following transaction failed: updateUndeliveredReason.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1006442,'The following transaction failed: updateSiteDuns.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1007148,'The following transaction failed: updateSite.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1006386,'The following transaction failed: updateSalesRep.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1006400,'The following transaction failed: updateSalesChannel.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1006512,'The following transaction failed: updateRelationship.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1007162,'The following transaction failed: updateGDPR.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1006288,'The following transaction failed: updateCustomerStatus.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1006274,'The following transaction failed: updateCustomer.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1009002,'The following transaction failed: updateCreditParty.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1006302,'The following transaction failed: updateContactStatus.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1006372,'The following transaction failed: updateContactMethod.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1001968,'The following transaction failed: updateContact.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1006344,'The following transaction failed: updateCAMAddress.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1006526,'The following transaction failed: searchCustomerByRelationship.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1003934,'The following transaction failed: searchCustomer.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1002404,'The following transaction failed: searchCAMContract.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008830,'The following transaction failed: retrofitServiceHelper.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1006456,'The following transaction failed: removeSiteDuns.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1006484,'The following transaction failed: removeCreditParty.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1003990,'The following transaction failed: reActivateCustomer.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1002555,'The following transaction failed: getTopNContractAlerts.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1003948,'The following transaction failed: getRelatedCustomerNumbers.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1006554,'The following transaction failed: getCustomerRelationship.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1006568,'The following transaction failed: getCustomer.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1003962,'The following transaction failed: getCamLocationIds.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1003976,'The following transaction failed: deleteCustomer.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1006260,'The following transaction failed: createCustomer.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1006428,'The following transaction failed: addSiteDuns.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1006330,'The following transaction failed: addSite.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1006498,'The following transaction failed: addRelationship.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1006414,'The following transaction failed: addNotes.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1006470,'The following transaction failed: addCreditParty.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1006358,'The following transaction failed: addContactMethod.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1001954,'The following transaction failed: addContact.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1007182,'The following transaction failed: SearchCAMCustomer.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004792,'The following transaction failed: RetrofitUSCAMContract.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1007347,'The following is required: stn_info_tp_cd');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1007408,'The following is required: stn_info_tp_cd');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1003904,'The following is required: state_country_tp_cd');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1002795,'The following is required: role_loc_st_tp_cd');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1000785,'The following is required: rm_num_tp_cd');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1000151,'The following is required: name');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1002750,'The following is required: name');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1002803,'The following is required: name');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1003912,'The following is required: name');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1007355,'The following is required: name');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1007416,'The following is required: name');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008923,'The following is required: name');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008934,'The following is required: contract_st_tp_cd');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008952,'The following is required: contract_st_reason_tp_cd');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1002742,'The following is required: contr_role_st_tp_cd');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004133,'The following is required: buid_tp_cd');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1001831,'The following is required: XStartDate');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1003246,'The following is required: XSalesChannel');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1003833,'The following is required: XPaymentTermCode');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1003825,'The following is required: XEndUserAuthCode');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1005953,'The following is required: XCreateDt');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1002496,'The following is required: XCAMLocationId');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008862,'The following is required: TaxIdType');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1002932,'The following is required: StartDate');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1001847,'The following is required: StartDate');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004748,'The following is required: SalesChannelId');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1007700,'The following is required: PartyType');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1007860,'The following is required: PartyId');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1007684,'The following is required: PartyId');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004141,'The following is required: Name');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1007764,'The following is required: LocationGroupId');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1007892,'The following is required: LocationGroupId');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004756,'The following is required: LinkedCurrencyCode');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004440,'The following is required: LinkedBuidStr');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004408,'The following is required: LangTpCd');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004772,'The following is required: LangTpCd');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1002926,'The following is required: EntityName');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004740,'The following is required: EndUserAuthCode');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1002912,'The following is required: CreatedSource');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1007676,'The following is required: ContractRoleType');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1007852,'The following is required: ContractRoleType');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1007668,'The following is required: ContractRoleId');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1007844,'The following is required: ContractRoleId');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1007828,'The following is required: ContractId');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1007644,'The following is required: ContractId');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1000290,'The following is required: ContractId');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1007836,'The following is required: ContractComponentId');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1007652,'The following is required: ContractComponentId');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1007908,'The following is required: ContactMethodType');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1007900,'The following is required: ContactMethodId');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1005454,'The following is required: CAMTaxIdentifierId');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1002837,'The following is required: CAMSrcUpdRuleIdPk');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1000217,'The following is required: CAMSalesRepIdPk');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004188,'The following is required: CAMRoleResponsibilityIdPk');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004673,'The following is required: CAMEndUserAuthXRefIdPk');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1007458,'The following is required: CAMDNRoleAddrGrouppkId');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1007553,'The following is required: CAMDNContMethGrouppkId');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004336,'The following is required: CAMBUIdXrefIdPk');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004424,'The following is required: BuidReferenceValue');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004416,'The following is required: BuidReferenceType');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004432,'The following is required: BuidReferenceDataCategory');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1007628,'The following is required: Buid');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1007812,'The following is required: Buid');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1007804,'The following is required: AdminContractId');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1007620,'The following is required: AdminContractId');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1007772,'The following is required: AddressId');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008786,'The following is not found: <param>.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004148,'The following is not correct: country_tp_cd');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008930,'The following is not correct: contract_st_tp_cd');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1000552,'The following is not correct: XStartDate');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1003624,'The following is not correct: XSplitToPurpose');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1003587,'The following is not correct: XSplitFromPurpose');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1002983,'The following is not correct: XRoleLocSt');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1007064,'The following is not correct: XLastUpdateDtUTC');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1006992,'The following is not correct: XLastUpdateDtUTC');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1005917,'The following is not correct: XLastUpdateDtUTC');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1005369,'The following is not correct: XLastUpdateDtUTC');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1005273,'The following is not correct: XLastUpdateDtUTC');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1005028,'The following is not correct: XLastUpdateDtUTC');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1006916,'The following is not correct: XLastUpdateDtUTC');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1002970,'The following is not correct: XInactReason');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1002996,'The following is not correct: XInactReason');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1003063,'The following is not correct: XInactReason');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1000564,'The following is not correct: XEndDate');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1006984,'The following is not correct: XCreateDtUTC');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1006912,'The following is not correct: XCreateDtUTC');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1005012,'The following is not correct: XCreateDtUTC');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1007060,'The following is not correct: XCreateDtUTC');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1005357,'The following is not correct: XCreateDtUTC');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1005989,'The following is not correct: XCreateDtUTC');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1005905,'The following is not correct: XCreateDtUTC');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1001843,'The following is not correct: XCreateDt');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1001909,'The following is not correct: XCreateDt');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1001897,'The following is not correct: XCreateDt');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1005261,'The following is not correct: XCreateDt');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1001118,'The following is not correct: XContractStDate');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1003050,'The following is not correct: XContrRoleSt');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1003315,'The following is not correct: StartDate');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1005567,'The following is not correct: StartDate');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004290,'The following is not correct: StartDate');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1000348,'The following is not correct: StartDate');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004272,'The following is not correct: RolePurpose');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1007790,'The following is not correct: RoleLocationEndDate');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1007930,'The following is not correct: RoleLocationEndDate');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1001669,'The following is not correct: RepAssignedDate');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1000355,'The following is not correct: RMNUM');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1007786,'The following is not correct: PartyInactivatedDate');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004404,'The following is not correct: LangTpCd');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1005591,'The following is not correct: ExpiryDate');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004454,'The following is not correct: ExpiryDate');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004778,'The following is not correct: ExpiryDate');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008610,'The following is not correct: EndUserAuthCode <EndUserAuthCode> and SalesChannelId <SalesChannelId> for given Currency Code <Currency_Val>.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004302,'The following is not correct: EndDate');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1005579,'The following is not correct: EndDate');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1003282,'The following is not correct: EndDate');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1001673,'The following is not correct: EndDate');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1007782,'The following is not correct: ContractRoleEndDate');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1007778,'The following is not correct: ContractEndDate');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008586,'The following is not correct: <ATTRIBUTE_TYPE> or <ATTRIBUTE_VALUE>');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008582,'The following is not correct: <ATTRIBUTE_TYPE> and <ATTRIBUTE_VALUE> for BUID <BUID>');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1006779,'The following is incorrect: id is null.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1002862,'The following is incorrect: id is null.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1002523,'The following is incorrect: id is null.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1002425,'The following is incorrect: id is null.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1007483,'The following is incorrect: id is null.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1007578,'The following is incorrect: id is null.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004604,'The following is incorrect: id is null.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1000242,'The following is incorrect: id is null.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004575,'The following is incorrect: id is null.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004213,'The following is incorrect: id is null.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1005479,'The following is incorrect: id is null.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004698,'The following is incorrect: id is null.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004361,'The following is incorrect: id is null.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004633,'The following is incorrect: id is null.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004548,'The following is incorrect: id is null.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004088,'The following is incorrect: SearchCAMCustomer has a child CAMCustomerSearch but the reference in CAMCustomerSearch is present and does not match the id from SearchCAMCustomer');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004070,'The following is incorrect: CAMCustomerSearch has a child PartialContractAdminSysKey but the reference in PartialContractAdminSysKey is present and does not match the id from CAMCustomerSearch');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004008,'The following is incorrect: CAMContractSearch has a child ContractSearch but the reference in ContractSearch is present and does not match the id from CAMContractSearch');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008618,'The currency value is invalid.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1005458,'The before image for the following is empty: CAMTaxIdentifier.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1002841,'The before image for the following is empty: CAMSrcUpdRule.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1000221,'The before image for the following is empty: CAMSalesRep.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004192,'The before image for the following is empty: CAMRoleResponsibility.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004677,'The before image for the following is empty: CAMEndUserAuthXRef.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1007462,'The before image for the following is empty: CAMDNRoleAddrGroup.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1007557,'The before image for the following is empty: CAMDNContMethGroup.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004340,'The before image for the following is empty: CAMBUIdXref.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008322,'The Funder relationship has been inactivated. Contact Credit / Collections to create a new relationship');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008642,'ServiceOrgName is required for AgreementFullName.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008338,'SearchCAMContract failed: Wrong inquiry level for either contract or party level.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008346,'SearchCAMContract failed: No contracts found for given search.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008362,'SearchCAMContract failed: No contacts found for given customer.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008342,'SearchCAMContract failed: Insufficient input data to search.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008350,'SearchCAMContract failed: Incorrect party pagination parameters.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008742,'Sales channel cannot be updated on a funder account.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008674,'RoleLocation Status cannot be updated.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1006775,'Read of the following record failed: CAMTaxIdentifier.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1005475,'Read of the following record failed: CAMTaxIdentifier.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1002858,'Read of the following record failed: CAMSrcUpdRule.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1000238,'Read of the following record failed: CAMSalesRep.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1002421,'Read of the following record failed: CAMSalesRep.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1002519,'Read of the following record failed: CAMSalesRep.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004209,'Read of the following record failed: CAMRoleResponsibility.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004694,'Read of the following record failed: CAMEndUserAuthXRef.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1007479,'Read of the following record failed: CAMDNRoleAddrGroup.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1007574,'Read of the following record failed: CAMDNContMethGroup.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004544,'Read of the following record failed: CAMBUIdXref.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004571,'Read of the following record failed: CAMBUIdXref.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004357,'Read of the following record failed: CAMBUIdXref.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004629,'Read of the following record failed: CAMBUIdXref.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004600,'Read of the following record failed: CAMBUIdXref.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004899,'Read of the following failed: XPersonName.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1000471,'Read of the following failed: XPerson.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1003719,'Read of the following failed: XPartyIdentification.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1000919,'Read of the following failed: XPartyContactMethod.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1000830,'Read of the following failed: XPartyAddress.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1006824,'Read of the following failed: XParty.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1005093,'Read of the following failed: XOrganizationName.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1002596,'Read of the following failed: XOrganization.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004507,'Read of the following failed: XContractRoleLocationPurpose.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1001179,'Read of the following failed: XContractRoleLocation.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1003039,'Read of the following failed: XContractRole.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1002480,'Read of the following failed: XContractRelationship.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1003552,'Read of the following failed: XContractPartyRoleRelationship.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1001102,'Read of the following failed: XContractComponent.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1000976,'Read of the following failed: XContract.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1007993,'Read of the following failed: XContactMethod.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1000536,'Read of the following failed: XContEquiv.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1007105,'Read of the following failed: XAdminNativeKey.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004972,'Read of the following failed: XAddress.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008614,'Phone Country Code length should be 3 digits');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008822,'PersonName is enddated.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008846,'Party Created by <parm> cannot be updated by <parm>.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008826,'OrganizationName is enddated.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008850,'No record found for email provided');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008366,'No matching parties found for the given identifier');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1009006,'No Site DUNS available for given PartyID and AddressId');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008518,'No Matching Address Found for Site-Duns.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008522,'Invalid link number for Relationship.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008654,'Invalid PurposeType for Phone RoleLocation.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008650,'Invalid PurposeType for PartyAddress RoleLocation.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008658,'Invalid PurposeType for Email RoleLocation.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008638,'Invalid Provider Reason for Full Company Name.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004891,'Insert of the following failed: XPersonName.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1000463,'Insert of the following failed: XPerson.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1003711,'Insert of the following failed: XPartyIdentification.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1000911,'Insert of the following failed: XPartyContactMethod.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1000822,'Insert of the following failed: XPartyAddress.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1006816,'Insert of the following failed: XParty.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1005085,'Insert of the following failed: XOrganizationName.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1002588,'Insert of the following failed: XOrganization.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004499,'Insert of the following failed: XContractRoleLocationPurpose.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1001171,'Insert of the following failed: XContractRoleLocation.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1003031,'Insert of the following failed: XContractRole.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1002472,'Insert of the following failed: XContractRelationship.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1003544,'Insert of the following failed: XContractPartyRoleRelationship.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1001094,'Insert of the following failed: XContractComponent.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1000968,'Insert of the following failed: XContract.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1007985,'Insert of the following failed: XContactMethod.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1000528,'Insert of the following failed: XContEquiv.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1007097,'Insert of the following failed: XAdminNativeKey.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004964,'Insert of the following failed: XAddress.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1005498,'Insert of the following failed: CAMTaxIdentifier.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1002881,'Insert of the following failed: CAMSrcUpdRule.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1000261,'Insert of the following failed: CAMSalesRep.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004232,'Insert of the following failed: CAMRoleResponsibility.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004717,'Insert of the following failed: CAMEndUserAuthXRef.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1007502,'Insert of the following failed: CAMDNRoleAddrGroup.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1007597,'Insert of the following failed: CAMDNContMethGroup.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004380,'Insert of the following failed: CAMBUIdXref.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008578,'Incomplete Customer Information (Missing either PrimaryBilling/PrimaryShipping/Owner contacts), please try again after some time.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008334,'Given BUID is not valid');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008814,'GetRelatedCustomerNumbers failed: No Data found for Given Search.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008810,'GetRelatedCustomerNumbers failed: Incorrect pagination parameters.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008806,'GetRelatedCustomerNumbers failed: AdminContractId or BusOrgunitId or XContractRelType is not present.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008802,'GetCamLocationIds failed: No Data found for Given Search.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008798,'GetCamLocationIds failed: Incorrect pagination parameters');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008794,'GetCamLocationIds failed : Either AdminContractId or BusOrgunitId is not present');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008422,'Error: XModifyBy is mandatory during Create and Update Customer At Contract level.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008306,'Error: Unable To Establish JDBC Connection');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008374,'Error: The Following is Required Contract Currency Type.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008382,'Error: The Following Is Required : XCreateBy during create customer at Contract level.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008398,'Error: The Following Is Required : TCRMContractRoleLocationBObj.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008394,'Error: The Following Is Required : TCRMContractPartyRoleBObj.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008390,'Error: The Following Is Required : TCRMContractComponentBObj.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008386,'Error: The Following Is Required : AgreementName.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008414,'Error: TCRMContractRoleLocationPurposeBObj Is Mandatory At TCRMContractRoleLocationBObj.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008310,'Error: SQL Execution Error');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008438,'Error: PartyAddress is mandatory for new party.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008406,'Error: Oracle Sequence Does not exits');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008358,'Error: No Record Found For Search Party.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008314,'Error: No Record Found For Search Contract.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008402,'Error: ContractRoleType cannot be updated.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008418,'Error: At-least one active primary CAMSalesRepBObj is required.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008410,'Error: At Least One TCRMPartyAddressBObj Is Mandatory At TCRMContractRoleLocationBObj.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008594,'ERROR: a duplicate party already exists, can not create.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7000104,'ERROR: XSplitToPurposeType is Mandatory');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7000101,'ERROR: XSplitToCustomerNumber is Mandatory');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7000103,'ERROR: XSplitToCAMLocationId is Mandatory');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7000102,'ERROR: XSplitToAddrSeqNum is Mandatory');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7000108,'ERROR: XSplitFromPurposeType is Mandatory');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7000105,'ERROR: XSplitFromCustomerNumber is Mandatory');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7000107,'ERROR: XSplitFromCAMLocationId is Mandatory');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7000106,'ERROR: XSplitFromAddrSeqNum is Mandatory');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008458,'ERROR: XPaymentTermType Cannot be blank when AgreementType {1000001}.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008470,'ERROR: XLegacyContractId is Mandatory');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (7000100,'ERROR: XLegacyCompanyName is Mandatory');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008590,'ERROR: XBUID is required at XAdminNativeKey Object.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008542,'ERROR: Validation for Partner / Vendor / End User / Retailer relationships.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008630,'ERROR: Update on Full Company Name is not allowed.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008606,'ERROR: The Given Party Address / Party Contact Method ID PK is not valid.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008818,'ERROR: The Following is Required : TCRMContractBObj.getBusOrgunitId.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008706,'ERROR: RoleLocation status type cannot be updated to null.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008318,'ERROR: RoleLocation status type cannot be inactive for Primary Billing or Primary Shipping or Primary Mailing Address.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008682,'ERROR: Role type can not be end dated for Primary RoleType.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008702,'ERROR: Role status type cannot be updated to null.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008690,'ERROR: Role Type cannot be updated from Primay Shipping to Shipping : Atleast one Primary Shipping RoleType is required.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008694,'ERROR: Role Type cannot be updated from Primay Mailing to Mailing : Atleast one Primary Mailing RoleType is required.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008686,'ERROR: Role Type cannot be updated from Primay Billing to Billing : Atleast one Primary Billing RoleType is required.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008710,'ERROR: Retailer, Partner, Vendor and End User relationship are only between two customer accounts.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008462,'ERROR: RepNum is Mandatory');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008466,'ERROR: RMNUMType is Mandatory');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008626,'ERROR: PurposeType mismatch identified in CONTACT address role location and role responsibility.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008574,'ERROR: Provided Link Customer does not match to any active contract.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008530,'ERROR: Primary Billing/Primary Shipping/Primary Mailing role type can not be end dated.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008450,'ERROR: Phone Number is Mandatory for Person for NON-DOM');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008454,'ERROR: Phone Number is Mandatory for Org');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008378,'ERROR: Person Party must be Required with Org Party.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008602,'ERROR: Owner role is required for adding a customer.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008646,'ERROR: Only one primary phones or emails is allowed in a contact.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008790,'ERROR: Occured while Converting Legacy state model to feature state model.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008714,'ERROR: Link relationship type is only between customer account and link account.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008570,'ERROR: Invalid character set has been passed.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008538,'ERROR: Invalid State and Country Code combination.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008546,'ERROR: Invalid Address.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008474,'ERROR: Input Request is having Only One ContractPartyRole of Role Type Owner{1000005}.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008426,'ERROR: Input Request having more than one primary billing contact. {Role Type 1000001}');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008430,'ERROR: Input Request having more than one primary Shipping contact. {Role Type 1000003}');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008434,'ERROR: Input Request having more than one Primary Mailing Contact. {Role Type 1000007}');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008718,'ERROR: Funder/Floorer relationship type is only between customer account and funder account.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008558,'ERROR: For shipping only customer, primary billing contact and billing contact is not allowed.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008554,'ERROR: For a Split Customer, PrimaryBilling and Billing Contact is not applicable.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008666,'ERROR: For Shipping RoleType{1000003,1000004} purposeType must be of Shipping {1000031,1000002} only For Address.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008662,'ERROR: For Mailing RoleType{1000007,1000008} purposeType must be of Mailing {1000029,1000003} only For Address.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008670,'ERROR: For Billing RoleType{1000001,1000002} purposeType must be of Billing {1000030,1000001} only For Address.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008622,'ERROR: Duplicate Purpose Type in RoleLocationPurpose.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008598,'ERROR: Currency Type can not be updated.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008698,'ERROR: Cross Role Type cannot be updated.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008526,'ERROR: Contract status type cannot be inactive for Primary role type.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008678,'ERROR: Contract status type cannot be inactive for Primary RoleType.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008534,'ERROR: Contract status type cannot be inactive for Person Owner role type.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008478,'ERROR :CAM Account is already part of another CAM Credit Party <ADMINPARTYID>');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008778,'ERROR : Stored Procedure failed to process Reactivate Customer.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008326,'ERROR : Stored Procedure failed to process Hard Delete Activation.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008562,'ERROR : Site DUNS does not belong to HQDUNS of existing Credit party.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008330,'ERROR : PRC_GETCAMLOCNID to get CAMLocationIDs.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008746,'ERROR : Only DSA can set the Contract Status Status to SH.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008446,'ERROR : HQ DUNS number is mandatory for Credit Org Party.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008738,'ERROR : Funder relationship not created because customer / funder sales channels do not match.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008750,'ERROR : Contract Status can be set to SH by DSA only if the Contract Status/RoleLocation Status is A.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008758,'ERROR : Contract Status can be set to A, H, D or S from SH by OMEGA.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008754,'ERROR : Contract Status can be set to A from SH only by DSA or OMEGA.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008442,'ERROR : Contract Does not exist, cannot create a Credit Pary without an existing Contract.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008730,'ERROR : (<Sales_Channel> : Previous Sales Channel is not in the DellPrint Path).');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008734,'ERROR : (<Sales_Channel> : Current Sales Channel is not in the DellPrint Path).');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1000265,'Duplicate primary key already exists.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1007601,'Duplicate primary key already exists.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1007506,'Duplicate primary key already exists.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1005502,'Duplicate primary key already exists.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1002885,'Duplicate primary key already exists.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004721,'Duplicate primary key already exists.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004384,'Duplicate primary key already exists.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004236,'Duplicate primary key already exists.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004895,'Delete of the following failed: XPersonName.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1000467,'Delete of the following failed: XPerson.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1003715,'Delete of the following failed: XPartyIdentification.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1000915,'Delete of the following failed: XPartyContactMethod.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1000826,'Delete of the following failed: XPartyAddress.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1006820,'Delete of the following failed: XParty.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1005089,'Delete of the following failed: XOrganizationName.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1002592,'Delete of the following failed: XOrganization.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004503,'Delete of the following failed: XContractRoleLocationPurpose.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1001175,'Delete of the following failed: XContractRoleLocation.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1003035,'Delete of the following failed: XContractRole.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1002476,'Delete of the following failed: XContractRelationship.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1003548,'Delete of the following failed: XContractPartyRoleRelationship.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1001098,'Delete of the following failed: XContractComponent.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1000972,'Delete of the following failed: XContract.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1007989,'Delete of the following failed: XContactMethod.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1000532,'Delete of the following failed: XContEquiv.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1007101,'Delete of the following failed: XAdminNativeKey.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1004968,'Delete of the following failed: XAddress.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008842,'Contract Created by <parm> cannot be updated by <parm>.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1007186,'Business proxy has failed');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008634,'AgreementFullName cannot be null for given ServiceOrgName.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1009004,'Admin Party Id not found');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008838,'A contractrole once is in InActive status, cannot be updated.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008834,'A contract once is in DeActive status, cannot be updated.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008774,'(reActivateCustomer failed: Failed to process ReActivation.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008550,'(ERROR: Invalid Address during search.');
Insert into CDERRMESSAGETP (ERR_MESSAGE_TP_CD,ERR_MESSAGE) values (1008722,'(ERROR: 3rd Party Leasing relationship type is only between active customer account and active funder account.');
